# 6.1 Threshold函数

In [1]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY)

print("img=\n",img)

print("t=",t)

print("rst=\n",rst)

img=
 [[160   0   8 252 227]
 [164  75 133 231 190]
 [ 71 123  62  25 239]
 [124  75 144 191 247]]
t= 127.0
rst=
 [[255   0   0 255 255]
 [255   0 255 255 255]
 [  0   0   0   0 255]
 [  0   0 255 255 255]]


In [3]:
img=cv2.imread("../images/lena.bmp")

t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY)

cv2.imshow("img",img)

cv2.imshow("rst",rst)

cv2.waitKey()

cv2.destroyAllWindows()

In [4]:

img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)

print("img=\n",img)

print("t=",t)

print("rst=\n",rst)

img=
 [[134  19  70  26 107]
 [ 83 250 231  11 228]
 [124  29 100 121  16]
 [203  31 140 100 204]]
t= 127.0
rst=
 [[  0 255 255 255 255]
 [255   0   0 255   0]
 [255 255 255 255 255]
 [  0 255   0 255   0]]


In [6]:
img=cv2.imread("../images/lena.bmp")
t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)

cv2.imshow("img",img)

cv2.imshow("rst",rst)

cv2.waitKey()

cv2.destroyAllWindows()

In [7]:
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)

print("img=\n",img)

print("t=",t)

print("rst=\n",rst)

img=
 [[161 198  66  78 131]
 [ 68  33  87  80 151]
 [101 205  67 168 138]
 [ 98 142  48 130  47]]
t= 127.0
rst=
 [[127 127  66  78 127]
 [ 68  33  87  80 127]
 [101 127  67 127 127]
 [ 98 127  48 127  47]]


In [11]:
img=cv2.imread("../images/lena.bmp")

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)

cv2.imshow("img",img)

cv2.imshow("rst",rst)

cv2.waitKey()

cv2.destroyAllWindows()

In [10]:
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)

print("img=\n",img)

print("t=",t)

print("rst=\n",rst)


img=
 [[223   3 173 130 216]
 [242  80 230 183 227]
 [210  15 176  27 226]
 [ 27 193  48 231 103]]
t= 127.0
rst=
 [[  0   3   0   0   0]
 [  0  80   0   0   0]
 [  0  15   0  27   0]
 [ 27   0  48   0 103]]


In [13]:
img=cv2.imread("../images/lena.bmp")

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)

cv2.imshow("img",img)

cv2.imshow("rst",rst)

cv2.waitKey()

cv2.destroyAllWindows()

In [15]:
img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO)

print("img=\n",img)

print("t=",t)

print("rst=\n",rst)

img=
 [[220 219   4 189  88]
 [222  95 187 145 140]
 [ 44  55  12 121 133]
 [236 122   7 213   5]]
t= 127.0
rst=
 [[220 219   0 189   0]
 [222   0 187 145 140]
 [  0   0   0   0 133]
 [236   0   0 213   0]]


In [14]:
img=cv2.imread("../images/lena.bmp")

t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO)

cv2.imshow("img",img)

cv2.imshow("rst",rst)

cv2.waitKey()

cv2.destroyAllWindows()