# 2.4 Numpy显示彩色图像的三通道值

In [1]:
import numpy as np
import cv2

img = np.zeros((300,300,3), dtype=np.uint8)
img[:, 0:100, 0] = 255
img[:, 100:200, 1] = 255
img[:, 200:300, 2] = 255

print("image=\n", img)
cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

image=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


以上代码，我们将三个通道的颜色值都显示在一张300x300像素排列的图片上，可以清楚地认识到图片末尾的值[0,1,2]的改变，读取到的颜色也是不一样的。所以对于[300, 300, 3]的彩色图像，一个三维数组，最后的三个通道，，每个通道决定了不同颜色，B-G-R的值。