# 3.2 CV2.add函数

In [1]:
import numpy as np
import cv2

img1 = np.random.randint(0, 256, size=[3,3], dtype=np.uint8)
img2 = np.random.randint(0, 256, size=[3,3], dtype=np.uint8)

print("img1=\n", img1)
print("img2=\n", img2)

img1=
 [[211  23 203]
 [176  80 183]
 [234 230 169]]
img2=
 [[218 151 223]
 [ 99 244 245]
 [207  66   4]]


In [2]:
img3=cv2.add(img1,img2)
print("cv2.add（img1,img2）=\n",img3)

cv2.add（img1,img2）=
 [[255 174 255]
 [255 255 255]
 [255 255 173]]


使用cv2.add函数进行两张图像的相加，像素值相加结果超过255的，则赋值为255，小于等于则按相加结果赋值。