# 8.2 形态学操作-膨胀

In [2]:
import cv2

import numpy as np

img=np.zeros((5,5),np.uint8)
img[2:3,1:4]=1
kernel=np.ones((3,1),np.uint8)
dilation=cv2.dilate(img,kernel)
print("img=\n",img)
print("kernel=\n",kernel)
print("dilation\n",dilation)

img=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
kernel=
 [[1]
 [1]
 [1]]
dilation
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [ ]:
import cv2

import numpy as np

o=cv2.imread("../images/dilation.png",cv2.IMREAD_UNCHANGED)

kernel=np.ones((9,9),np.uint8)

dilation=cv2.dilate(o,kernel)

cv2.imshow("original",o)

cv2.imshow("dilation",dilation)

cv2.waitKey()

cv2.destroyAllWindows()

In [4]:
import cv2

import numpy as np

o=cv2.imread("../images/dilation.png",cv2.IMREAD_UNCHANGED)

kernel=np.ones((5,5),np.uint8)

dilation=cv2.dilate(o,kernel,iterations=9)

cv2.imshow("original",o)

cv2.imshow("dilation",dilation)

cv2.waitKey()

cv2.destroyAllWindows()