# 4.3 alpha通道

In [2]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,3,3],dtype=np.uint8)

bgra=cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)

print("img=\n",img)

print("bgra=\n",bgra)

b,g,r,a=cv2.split(bgra)

print("a=\n",a)

a[:,:]=125

bgra=cv2.merge([b,g,r,a])

print("bgra=\n",bgra)

img=
 [[[ 81  52 253]
  [251  83  34]
  [114  43 221]]

 [[ 91 247  85]
  [ 62 239 253]
  [ 26 128 150]]]
bgra=
 [[[ 81  52 253 255]
  [251  83  34 255]
  [114  43 221 255]]

 [[ 91 247  85 255]
  [ 62 239 253 255]
  [ 26 128 150 255]]]
a=
 [[255 255 255]
 [255 255 255]]
bgra=
 [[[ 81  52 253 125]
  [251  83  34 125]
  [114  43 221 125]]

 [[ 91 247  85 125]
  [ 62 239 253 125]
  [ 26 128 150 125]]]


In [4]:
img=cv2.imread("../images/lenacolor.png")

bgra=cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)

b,g,r,a=cv2.split(bgra)

a[:,:]=125

bgra125=cv2.merge([b,g,r,a])

a[:,:]=0

bgra0=cv2.merge([b,g,r,a])

cv2.imshow("img",img)

cv2.imshow("bgra",bgra)

cv2.imshow("bgra125",bgra125)

cv2.imshow("bgra0",bgra0)

cv2.waitKey()

cv2.destroyAllWindows()

cv2.imwrite("bgra.png",bgra)

cv2.imwrite("bgra125.png",bgra125)

cv2.imwrite("bgra0.png",bgra0)

True