# 2.7 使用Numpy.array访问元素

In [1]:
import numpy as np
img=np.random.randint(10, 99, size=[5, 5], dtype=np.uint8)
print("img\n", img)
print("读取像素点img.item(3,2)=", img.item(3, 2))
img.itemset((3, 2), 255)
print("修改后img=\n", img)
print(img.item(3, 2))


img
 [[69 71 53 39 39]
 [92 40 24 10 22]
 [40 57 88 95 72]
 [82 71 89 40 17]
 [33 62 54 95 69]]
读取像素点img.item(3,2)= 89
修改后img=
 [[ 69  71  53  39  39]
 [ 92  40  24  10  22]
 [ 40  57  88  95  72]
 [ 82  71 255  40  17]
 [ 33  62  54  95  69]]
255


通过函数item()可以高效地访问图像的像素点，语法：item（行，列）
通过函数itemset()可以修改像素值，语法：itemset（索引值，新值）