# 9.1 Sobel算子

In [4]:
import cv2
import numpy as np
img=np.random.randint(-256,256,size=[4,5],dtype=np.int16)
rst=cv2.convertScaleAbs(img)
print("img=\n",img)
print("rst=\n",rst)
cv2.imshow('rst',rst)

cv2.waitKey()
cv2.destroyAllWindows()

img=
 [[-149 -101  162  -92 -248]
 [-245  246  227 -189   82]
 [ 172  100 -246  109   -7]
 [ 178 -208   42  232 -239]]
rst=
 [[149 101 162  92 248]
 [245 246 227 189  82]
 [172 100 246 109   7]
 [178 208  42 232 239]]


In [7]:
import cv2


o=cv2.imread('../images/sobel.png',cv2.IMREAD_GRAYSCALE)

Sobelx=cv2.Sobel(o,-1,1,0)

cv2.imshow("original",o)

cv2.imshow("x",Sobelx)

cv2.waitKey()

cv2.destroyAllWindows()

In [9]:
import cv2


o=cv2.imread('../images/sobel.png',cv2.IMREAD_GRAYSCALE)

Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)

Sobelx=cv2.convertScaleAbs(Sobelx)

cv2.imshow("original",o)

cv2.imshow("x",Sobelx)

cv2.waitKey()

cv2.destroyAllWindows()

In [10]:
import cv2


o=cv2.imread('../images/sobel.png',cv2.IMREAD_GRAYSCALE)

Sobelx=cv2.Sobel(o,cv2.CV_64F,0,1)

Sobelx=cv2.convertScaleAbs(Sobelx)

cv2.imshow("original",o)

cv2.imshow("x",Sobelx)

cv2.waitKey()

cv2.destroyAllWindows()

In [11]:
import cv2


o=cv2.imread('../images/sobel.png',cv2.IMREAD_GRAYSCALE)

Sobelx=cv2.Sobel(o,cv2.CV_64F,1,1)

Sobelx=cv2.convertScaleAbs(Sobelx)

cv2.imshow("original",o)

cv2.imshow("x",Sobelx)

cv2.waitKey()

cv2.destroyAllWindows()

In [13]:
import cv2

o=cv2.imread('../images/sobel.png',cv2.IMREAD_GRAYSCALE)

Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)

Sobely=cv2.Sobel(o,cv2.CV_64F,0,1)

Sobelx=cv2.convertScaleAbs(Sobelx)

Sobely=cv2.convertScaleAbs(Sobely)

Sobelxy=cv2.addWeighted(Sobelx,0.5,Sobely,0.5,0)

cv2.imshow("original",o)

cv2.imshow("xy",Sobelxy)

cv2.waitKey()

cv2.destroyAllWindows()

In [14]:
import cv2
o=cv2.imread('../images/lena.bmp',cv2.IMREAD_GRAYSCALE)
Sobelx=cv2.Sobel(o,cv2.CV_64F,1,0)
Sobely=cv2.Sobel(o,cv2.CV_64F,0,1)
Sobelx=cv2.convertScaleAbs(Sobelx)
Sobely=cv2.convertScaleAbs(Sobely)
Sobelxy=cv2.addWeighted(Sobelx,0.5,Sobely,0.5,0)
Sobelxy11=cv2.Sobel(o,cv2.CV_64F,1,1)
Sobelxy11=cv2.convertScaleAbs(Sobelxy11)
cv2.imshow("original",o)
cv2.imshow("xy",Sobelxy)
cv2.imshow("xy11",Sobelxy11)
cv2.waitKey()
cv2.destroyAllWindows()