# 3.4 图像加权和

In [1]:
import numpy as np
import cv2

img1 = np.ones((3,4), dtype=np.uint8) * 100
img2 = np.ones((3,4), dtype=np.uint8) * 10

gamma = 3
img3 = cv2.addWeighted(img1, 0.6, img2, 5, gamma)
print(img3)


[[113 113 113 113]
 [113 113 113 113]
 [113 113 113 113]]


图像的加权和，使用两幅图像的像素值，并且分配不同的权重给到两个图像，使用cv2.addWeighted()函数实现图像的加权和，语法：dst=cv2.addWeighted（src1,alpha,src2,beta,gamma）。该函数实现的功能是dst=src1×alpha+src2×beta+gamma。可以将上式理解为“结果图像=图像1×系数1+图像2×系数2+亮度调节量”。

In [3]:
a=cv2.imread("../images/lenacolor.png")
b=cv2.imread("../images/lenacolor.png")
result=cv2.addWeighted(a, 0.5, b, 0.5, 0)

cv2.imshow("boat",a)
cv2.imshow("lena",b)
cv2.imshow("result",result)

cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
import cv2
lena=cv2.imread("../images/lenacolor.png",cv2.IMREAD_UNCHANGED)
dollar=cv2.imread("../images/starry_night.jpg",cv2.IMREAD_UNCHANGED)

cv2.imshow("lena",lena)
cv2.imshow("dollar",dollar)

face1=lena[220:400,250:350]
face2=dollar[160:340,200:300]

add=cv2.addWeighted(face1,0.6,face2,0.4,0)
dollar[160:340,200:300]=add
cv2.imshow("result",dollar)

cv2.waitKey()
cv2.destroyAllWindows()

以上都是使用addWighter()函数对图像进行混合计算，加权混合的方式。