# 3.7 掩模

In [2]:
import cv2

import numpy as np

img1=np.ones((4,4),dtype=np.uint8)*3

img2=np.ones((4,4),dtype=np.uint8)*5

mask=np.ones((4,4),dtype=np.uint8)

mask[2:4,2:4]=1

img3=np.ones((4,4),dtype=np.uint8)*66

print("img1=\n",img1)

print("img2=\n",img2)

print("mask=\n",mask)

print("初始值img3=\n",img3)

img3=cv2.add(img1,img2,mask=mask)

print("求和后img3=\n",img3)

img1=
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
img2=
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
mask=
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
初始值img3=
 [[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]
求和后img3=
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [3]:
import cv2
import numpy as np

a=cv2.imread("../images/lena.bmp",1)
w,h,c=a.shape
mask=np.zeros((w,h),dtype=np.uint8)
mask[100:400,200:400]=255
mask[100:500,100:200]=255

c=cv2.bitwise_and(a,a,mask)
print("a.shape=",a.shape)
print("mask.shape=",mask.shape)

cv2.imshow("a",a)
cv2.imshow("mask",mask)
cv2.imshow("c",c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shape= (512, 512, 3)
mask.shape= (512, 512)


In [ ]:
以上使用cv2.add()中掩模参数