# 4.1 图像类型转换案例


In [3]:
import cv2 
import numpy as np

img = np.random.randint(0,256,size=[2,4,3],dtype=np.uint8)
rst = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print("img=\n", img)
print("rst=\n", rst)
print("像素点(1,0)直接计算得到的值=", img[1,0,0]*0.114 + img[1,0,1]*0.587+img[1,0,2]*0.299)
print("像素点(1,0)使用公式cv2.cvtColor()转换值=", rst[1,0])

img=
 [[[124  17 146]
  [ 45 250 138]
  [117  14 172]
  [ 41 250 170]]

 [[109 205 168]
  [ 65   7  63]
  [133 213 132]
  [169   7  11]]]
rst=
 [[ 68 193  73 202]
 [183  30 180  27]]
像素点(1,0)直接计算得到的值= 182.993
像素点(1,0)使用公式cv2.cvtColor()转换值= 183


# 类型转换函数
使用cv2.cvtColor（）函数实现色彩空间的变换。该函数能够实现多个色彩空间之间的转换。其语法格式为：

dst=cv2.cvtColor（src,code[,dstCn]）

1. dst表示输出图像，与原始输入图像具有同样的数据类型和深度。

2. src表示原始输入图像。可以是8位无符号图像、16位无符号图像，或者单精度浮点数等。

3. code是色彩空间转换码，表4-2展示了其枚举值。

4. dstCn 是目标图像的通道数。如果参数为默认的0，则通道数自动通过原始输入图像和code得到。

In [5]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,4],dtype=np.uint8)

rst=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

print("img=\n",img)

print("rst=\n",rst)

img=
 [[ 12 141 146 140]
 [142 152  93 250]]
rst=
 [[[ 12  12  12]
  [141 141 141]
  [146 146 146]
  [140 140 140]]

 [[142 142 142]
  [152 152 152]
  [ 93  93  93]
  [250 250 250]]]


In [6]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,4,3],dtype=np.uint8)

rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

bgr=cv2.cvtColor(rgb,cv2.COLOR_RGB2BGR)

print("img=\n",img)

print("rgb=\n",rgb)

print("bgr=\n",bgr)

img=
 [[[199  39 191]
  [219 162 183]
  [118  90 173]
  [ 65 190  83]]

 [[143  49  53]
  [115 243 233]
  [ 46 225  44]
  [ 63  86  64]]]
rgb=
 [[[191  39 199]
  [183 162 219]
  [173  90 118]
  [ 83 190  65]]

 [[ 53  49 143]
  [233 243 115]
  [ 44 225  46]
  [ 64  86  63]]]
bgr=
 [[[199  39 191]
  [219 162 183]
  [118  90 173]
  [ 65 190  83]]

 [[143  49  53]
  [115 243 233]
  [ 46 225  44]
  [ 63  86  64]]]


In [9]:
import cv2

lena=cv2.imread("../images/lenacolor.png")

gray=cv2.cvtColor(lena,cv2.COLOR_BGR2GRAY)

rgb=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)

#==========打印shape============

print("lena.shape=",lena.shape)

print("gray.shape=",gray.shape)

print("rgb.shape=",rgb.shape)

#==========显示效果============

cv2.imshow("lena",lena)

cv2.imshow("gray",gray)

cv2.imshow("rgb",rgb)

cv2.waitKey()

cv2.destroyAllWindows()

#运行程序，会显示各个图像的shape属性：

lena.shape=(512,512,3)

gray.shape=(512,512)

rgb.shape=(512,512,3)

lena.shape= (512, 512, 3)
gray.shape= (512, 512)
rgb.shape= (512, 512, 3)


In [12]:
import cv2

lena=cv2.imread("../images/lenacolor.png")

rgb=cv2.cvtColor(lena,cv2.COLOR_BGR2RGB)

cv2.imshow("lena",lena)

cv2.imshow("rgb",rgb)

cv2.waitKey()

cv2.destroyAllWindows()