# 3.5 按位与运算

In [1]:
import cv2
import numpy as np

a=np.random.randint(0,255,(5,5),dtype=np.uint8)
b=np.zeros((5,5),dtype=np.uint8)

b[0:3,0:3]=255
b[4,4]=255

c=cv2.bitwise_and(a,b)
print("a=\n",a)
print("b=\n",b)
print("c=\n",c)

a=
 [[175  99  45 169 177]
 [237 236 165   1  94]
 [191  92 226  57 157]
 [111 185 245 130 114]
 [ 77 197 204 128 139]]
b=
 [[255 255 255   0   0]
 [255 255 255   0   0]
 [255 255 255   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 255]]
c=
 [[175  99  45   0   0]
 [237 236 165   0   0]
 [191  92 226   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 139]]


In [2]:
import cv2
import numpy as np

a=cv2.imread("../images/lena.bmp",0)

b=np.zeros(a.shape,dtype=np.uint8)

b[100:400,200:400]=255

b[100:500,100:200]=255

c=cv2.bitwise_and(a,b)
print("a.shape=",a.shape)

print("b.shape=",b.shape)


cv2.imshow("a",a)

cv2.imshow("b",b)

cv2.imshow("c",c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shape= (512, 512)
b.shape= (512, 512)


In [3]:
import cv2
import numpy as np

a=cv2.imread("../images/lena.bmp",1)

b=np.zeros(a.shape,dtype=np.uint8)

b[100:400,200:400]=255

b[100:500,100:200]=255

c=cv2.bitwise_and(a,b)
print("a.shape=",a.shape)

print("b.shape=",b.shape)

cv2.imshow("a",a)

cv2.imshow("b",b)

cv2.imshow("c",c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shape= (512, 512, 3)
b.shape= (512, 512, 3)


使用cv2.bitwise_and（）函数来实现按位与运算，其语法格式为：dst=cv2.bitwise_and（src1,src2[,mask]]）,需要注意的是，如果是彩色图像，需要使用同样三通道的掩模图才可以。