# 8.1 形态学操作-腐蚀

In [1]:
import cv2
import numpy as np

#腐蚀操作中，需要定义卷积和大小和迭代的次数，如果迭代多，核越大 腐蚀越严重
img=np.zeros((5,5),np.uint8)
img[1:4,1:4]=1
kernel=np.ones((3,1),np.uint8)
erosion=cv2.erode(img,kernel)
print("img=\n",img)
print("kernel=\n",kernel)
print("erosion=\n",erosion)

img=
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
kernel=
 [[1]
 [1]
 [1]]
erosion=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [2]:
o=cv2.imread("../images/erode.png",cv2.IMREAD_UNCHANGED)

kernel=np.ones((5,5),np.uint8)

erosion=cv2.erode(o,kernel)

cv2.imshow("orriginal",o)

cv2.imshow("erosion",erosion)

cv2.waitKey()

cv2.destroyAllWindows()

In [7]:
o=cv2.imread("../images/erode.png",cv2.IMREAD_UNCHANGED)

kernel=np.ones((6,6),np.uint8)

erosion=cv2.erode(o,kernel, iterations=3)

cv2.imshow("orriginal",o)

cv2.imshow("erosion",erosion)

cv2.waitKey()

cv2.destroyAllWindows()