# 3.1 图像的加号运算运算符

In [1]:
import numpy as np

img1 = np.random.randint(0, 256, size=[3,3], dtype=np.uint8)
img2 = np.random.randint(0, 256, size=[3,3], dtype=np.uint8)

print("img1=\n", img1)
print("img2=\n", img2)
print("img1+img2=\n", img1+img2)

img1=
 [[114 205 115]
 [187 169  31]
 [206 214  95]]
img2=
 [[176 125 215]
 [202 112 191]
 [ 75 193 185]]
img1+img2=
 [[ 34  74  74]
 [133  25 222]
 [ 25 151  24]]


常规的加法运算，会对像素值相加大于256的取模，小于的则用相加的结果作为像素值。