# 5.5 重映射

In [1]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[4,5],dtype=np.uint8)

rows,cols=img.shape

mapx=np.ones(img.shape,np.float32)*3

mapy=np.ones(img.shape,np.float32)*0

rst=cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)

print("img=\n",img)

print("mapx=\n",mapx)

print("mapy=\n",mapy)

print("rst=\n",rst)

img=
 [[  4  95 130 197 197]
 [117 218 244  76 248]
 [ 91   8  65  92 130]
 [127  11   5  42  33]]
mapx=
 [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
mapy=
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
rst=
 [[197 197 197 197 197]
 [197 197 197 197 197]
 [197 197 197 197 197]
 [197 197 197 197 197]]
