# 2.5 访问与修改图像的三维数组

In [2]:
import numpy as np
img = np.zeros((2,4,3), dtype=np.uint8)
print("img=\n", img)
print("读取像素点[0,3]=", img[0,3])
print("读取像素点[1,2,2]=", img[1,2,2])
img[0, 3]=255
img[0, 0]=[66, 77, 88]
img[1, 2, 2] = 4
img[1, 1, 1] = 3
img[0, 2, 0] = 5
print("修改后img\n", img)
print("读取修改后像素点img[1,2,2]=", img[1,2,2])


img=
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
读取像素点[0,3]= [0 0 0]
读取像素点[1,2,2]= 0
修改后img
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
读取修改后像素点img[1,2,2]= 4


通过以上代码，我们可以看到如何对一个三维数组的图像矩阵进行读写和修改