# 5.1 缩放

In [1]:
import cv2

import numpy as np

img=np.ones([2,4,3],dtype=np.uint8)

size=img.shape[:2]

rst=cv2.resize(img,size)

print("img.shape=\n",img.shape)

print("img=\n",img)

print("rst.shape=\n",rst.shape)

print("rst=\n",rst)

img.shape=
 (2, 4, 3)
img=
 [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
rst.shape=
 (4, 2, 3)
rst=
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


这里需要注意的是shape属性里是（行数，列数），而dsize属性里是（列数，行数）

In [3]:
img=cv2.imread("../images/lenacolor.png")

rows,cols=img.shape[:2]

size=(int(cols*0.9),int(rows*0.5))

rst=cv2.resize(img,size)

print("img.shape=",img.shape)

print("rst.shape=",rst.shape)

img.shape= (512, 512, 3)
rst.shape= (256, 460, 3)


使用dsize行列数的方式进行缩放

In [4]:
img=cv2.imread("../images/lenacolor.png")

rst=cv2.resize(img,None,fx=2,fy=0.5)

print("img.shape=",img.shape)

print("rst.shape=",rst.shape)

img.shape= (512, 512, 3)
rst.shape= (256, 1024, 3)


使用fx,fy参数进行缩放。

使用函数cv2.resize（）实现对图像的缩放，
语法：dst=cv2.resize（src,dsize[,fx[,fy[,interpolation]]]）

● src代表需要缩放的原始图像。

● dsize代表输出图像大小。

● fx代表水平方向的缩放比例。

● fy代表垂直方向的缩放比例。

● interpolation代表插值方式