# 4.1 图像类型转换案例


In [1]:
import cv2 
import numpy as np

img = np.random.randint(0,256,size=[2,4,3],dtype=np.uint8)
rst = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print("img=\n", img)
print("rst=\n", rst)
print("像素点(1,0)直接计算得到的值=", img[1,0,0]*0.114 + img[1,0,1]*0.587+img[1,0,2]*0.299)
print("像素点(1,0)使用公式cv2.cvtColor()转换值=", rst[1,0])

img=
 [[[253  91 237]
  [102  43 210]
  [158 183 190]
  [110  91 145]]

 [[ 28  85  48]
  [215  33 181]
  [250  24  96]
  [239  96 164]]]
rst=
 [[153 100 182 109]
 [ 67  98  71 133]]
像素点(1,0)直接计算得到的值= 67.439
像素点(1,0)使用公式cv2.cvtColor()转换值= 67


# 类型转换函数
使用cv2.cvtColor（）函数实现色彩空间的变换。该函数能够实现多个色彩空间之间的转换。其语法格式为：

dst=cv2.cvtColor（src,code[,dstCn]）

1. dst表示输出图像，与原始输入图像具有同样的数据类型和深度。

2. src表示原始输入图像。可以是8位无符号图像、16位无符号图像，或者单精度浮点数等。

3. code是色彩空间转换码，表4-2展示了其枚举值。

4. dstCn 是目标图像的通道数。如果参数为默认的0，则通道数自动通过原始输入图像和code得到。

In [2]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,4],dtype=np.uint8)

rst=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

print("img=\n",img)

print("rst=\n",rst)

img=
 [[169  32 217 167]
 [182 208 240 193]]
rst=
 [[[169 169 169]
  [ 32  32  32]
  [217 217 217]
  [167 167 167]]

 [[182 182 182]
  [208 208 208]
  [240 240 240]
  [193 193 193]]]


In [3]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,4,3],dtype=np.uint8)

rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

bgr=cv2.cvtColor(rgb,cv2.COLOR_RGB2BGR)

print("img=\n",img)

print("rgb=\n",rgb)

print("bgr=\n",bgr)

img=
 [[[ 53  28  42]
  [125  24 233]
  [161 246   3]
  [214  58   7]]

 [[168 189 200]
  [  4 218  58]
  [ 39   5 141]
  [192 156  16]]]
rgb=
 [[[ 42  28  53]
  [233  24 125]
  [  3 246 161]
  [  7  58 214]]

 [[200 189 168]
  [ 58 218   4]
  [141   5  39]
  [ 16 156 192]]]
bgr=
 [[[ 53  28  42]
  [125  24 233]
  [161 246   3]
  [214  58   7]]

 [[168 189 200]
  [  4 218  58]
  [ 39   5 141]
  [192 156  16]]]


In [4]:
import cv2

lena=cv2.imread("../images/lenacolor.png")

gray=cv2.cvtColor(lena,cv2.COLOR_BGR2GRAY)

rgb=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)

#==========打印shape============

print("lena.shape=",lena.shape)

print("gray.shape=",gray.shape)

print("rgb.shape=",rgb.shape)

#==========显示效果============

cv2.imshow("lena",lena)

cv2.imshow("gray",gray)

cv2.imshow("rgb",rgb)

cv2.waitKey()

cv2.destroyAllWindows()

#运行程序，会显示各个图像的shape属性：

lena.shape=(512,512,3)

gray.shape=(512,512)

rgb.shape=(512,512,3)

lena.shape= (512, 512, 3)
gray.shape= (512, 512)
rgb.shape= (512, 512, 3)


In [5]:
import cv2

lena=cv2.imread("../images/lenacolor.png")

rgb=cv2.cvtColor(lena,cv2.COLOR_BGR2RGB)

cv2.imshow("lena",lena)

cv2.imshow("rgb",rgb)

cv2.waitKey()

cv2.destroyAllWindows()