# 4.2 HSV色彩空间

In [1]:
import cv2

import numpy as np

#=========测试一下OpenCV中蓝色的HSV模式值=============

imgBlue=np.zeros([1,1,3],dtype=np.uint8)

imgBlue[0,0,0]=255

Blue=imgBlue

BlueHSV=cv2.cvtColor(Blue,cv2.COLOR_BGR2HSV)

print("Blue=\n",Blue)

print("BlueHSV=\n",BlueHSV)

#=========测试一下OpenCV中绿色的HSV模式值=============

imgGreen=np.zeros([1,1,3],dtype=np.uint8)

imgGreen[0,0,1]=255

Green=imgGreen

GreenHSV=cv2.cvtColor(Green,cv2.COLOR_BGR2HSV)

print("Green=\n",Green)

print("GreenHSV=\n",GreenHSV)

#=========测试一下OpenCV中红色的HSV模式值=============

imgRed=np.zeros([1,1,3],dtype=np.uint8)

imgRed[0,0,2]=255

Red=imgRed

RedHSV=cv2.cvtColor(Red,cv2.COLOR_BGR2HSV)

print("Red=\n",Red)

print("RedHSV=\n",RedHSV)

Blue=
 [[[255   0   0]]]
BlueHSV=
 [[[120 255 255]]]
Green=
 [[[  0 255   0]]]
GreenHSV=
 [[[ 60 255 255]]]
Red=
 [[[  0   0 255]]]
RedHSV=
 [[[  0 255 255]]]


In [3]:
img=np.random.randint(0,256,size=[5,5],dtype=np.uint8)

min=100

max=200

mask=cv2.inRange(img,min,max)

print("img=\n",img)

print("mask=\n",mask)

img=
 [[233 206 166 230 240]
 [ 95 168  23 173 157]
 [ 32 227 117   8 149]
 [199  35 115 186  29]
 [100 239 119  18  17]]
mask=
 [[  0   0 255   0   0]
 [  0 255   0 255 255]
 [  0   0 255   0 255]
 [255   0 255 255   0]
 [255   0 255   0   0]]


以上代码通过cv2.inRange函数判断图像内像素点的像素值是否在指定的范围内，语法：dst=cv2.inRange（src,lowerb,upperb）

● dst表示输出结果，大小和src一致。

● src表示要检查的数组或图像。

● lowerb表示范围下界。

● upperb表示范围上界。

返回值dst与src等大小，其值取决于src中对应位置上的值是否处于区间[lowerb,upperb]内：

● 如果src值处于该指定区间内，则dst中对应位置上的值为255。

● 如果src值不处于该指定区间内，则dst中对应位置上的值为0。

In [4]:
img=np.ones([5,5],dtype=np.uint8)*9

mask=np.zeros([5,5],dtype=np.uint8)

mask[0:3,0]=1

mask[2:5,2:4]=1

roi=cv2.bitwise_and(img,img,mask=mask)

print("img=\n",img)

print("mask=\n",mask)

print("roi=\n",roi)

img=
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
mask=
 [[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 1 0]
 [0 0 1 1 0]
 [0 0 1 1 0]]
roi=
 [[9 0 0 0 0]
 [9 0 0 0 0]
 [9 0 9 9 0]
 [0 0 9 9 0]
 [0 0 9 9 0]]


通过mask设置了两个感兴趣区域（掩模）。后续通过在按位与运算中设置掩模的方式，将原始图像img内这两部分的值保留显示，而将其余部分的值置零

In [5]:
opencv=cv2.imread("../images/opencv-logo.png")

hsv=cv2.cvtColor(opencv,cv2.COLOR_BGR2HSV)

cv2.imshow('opencv',opencv)

#=============指定蓝色值的范围=============

minBlue=np.array([110,50,50])

maxBlue=np.array([130,255,255])

#确定蓝色区域

mask=cv2.inRange(hsv,minBlue,maxBlue)

#通过掩码控制的按位与运算，锁定蓝色区域

blue=cv2.bitwise_and(opencv,opencv,mask=mask)

cv2.imshow('blue',blue)

#=============指定绿色值的范围=============

minGreen=np.array([50,50,50])

maxGreen=np.array([70,255,255])

#确定绿色区域
mask=cv2.inRange(hsv,minGreen,maxGreen)

#通过掩码控制的按位与运算，锁定绿色区域

green=cv2.bitwise_and(opencv,opencv,mask=mask)

cv2.imshow('green',green)

#=============指定红色值的范围=============

minRed=np.array([0,50,50])

maxRed=np.array([30,255,255])

#确定红色区域

mask=cv2.inRange(hsv,minRed,maxRed)

#通过掩码控制的按位与运算，锁定红色区域

red=cv2.bitwise_and(opencv,opencv,mask=mask)

cv2.imshow('red',red)

cv2.waitKey()

cv2.destroyAllWindows()

通过HSV色彩空间下的热定颜色区间，我们提取出来一个颜色范围内的图像信息，再通过掩码进行按位与运算，提取出来制定颜色的图像信息。

In [6]:


img=cv2.imread("../images/lesson2.png")

hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

h,s,v=cv2.split(hsv)

minHue=5

maxHue=170

hueMask=cv2.inRange(h,minHue,maxHue)

minSat=25

maxSat=166

satMask=cv2.inRange(s,minSat,maxSat)

mask=hueMask & satMask

roi=cv2.bitwise_and(img,img,mask=mask)

cv2.imshow("img",img)

cv2.imshow("ROI",roi)

cv2.waitKey()

cv2.destroyAllWindows()

以上代码提取图像内的肤色，提取后的图像只保留了人脸的肤色信息。


In [8]:
img=cv2.imread("../images/barbara.png")

hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

h,s,v=cv2.split(hsv)

v[:,:]=255

newHSV=cv2.merge([h,s,v])

art=cv2.cvtColor(newHSV,cv2.COLOR_HSV2BGR)

cv2.imshow("img",img)

cv2.imshow("art",art)

cv2.waitKey()

cv2.destroyAllWindows()