# 4.3 alpha通道

In [1]:
import cv2

import numpy as np

img=np.random.randint(0,256,size=[2,3,3],dtype=np.uint8)

bgra=cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)

print("img=\n",img)

print("bgra=\n",bgra)

b,g,r,a=cv2.split(bgra)

print("a=\n",a)

a[:,:]=125

bgra=cv2.merge([b,g,r,a])

print("bgra=\n",bgra)

img=
 [[[ 70 134  14]
  [227 230  20]
  [123  63  12]]

 [[170 144  72]
  [157  97  63]
  [125  73 253]]]
bgra=
 [[[ 70 134  14 255]
  [227 230  20 255]
  [123  63  12 255]]

 [[170 144  72 255]
  [157  97  63 255]
  [125  73 253 255]]]
a=
 [[255 255 255]
 [255 255 255]]
bgra=
 [[[ 70 134  14 125]
  [227 230  20 125]
  [123  63  12 125]]

 [[170 144  72 125]
  [157  97  63 125]
  [125  73 253 125]]]


In [2]:
img=cv2.imread("../images/lenacolor.png")

bgra=cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)

b,g,r,a=cv2.split(bgra)

a[:,:]=125

bgra125=cv2.merge([b,g,r,a])

a[:,:]=0

bgra0=cv2.merge([b,g,r,a])

cv2.imshow("img",img)

cv2.imshow("bgra",bgra)

cv2.imshow("bgra125",bgra125)

cv2.imshow("bgra0",bgra0)

cv2.waitKey()

cv2.destroyAllWindows()

cv2.imwrite("bgra.png",bgra)

cv2.imwrite("bgra125.png",bgra125)

cv2.imwrite("bgra0.png",bgra0)

True