# 2.10 Item操作彩色图像

In [1]:
import numpy as np

img = np.random.randint(10,99,size=[2,4,3], dtype=np.uint8)
print("img=\n",img)
print("读取像素点img[1,2,0]=", img.item(1,2,0))
print("读取像素点img[0,2,1]=", img.item(0,2,1))
print("读取像素点img[1,0,2]=", img.item(1,0,2))

img=
 [[[64 26 12]
  [77 13 42]
  [71 80 27]
  [67 44 96]]

 [[27 61 40]
  [84 80 68]
  [63 66 47]
  [36 80 66]]]
读取像素点img[1,2,0]= 63
读取像素点img[0,2,1]= 80
读取像素点img[1,0,2]= 40


In [2]:
img.itemset((1,2,0), 255)
img.itemset((0,2,1), 255)
img.itemset((1,0,2), 255)

print("修改后img=\n",img)
print("读取像素点img[1,2,0]=", img.item(1,2,0))
print("读取像素点img[0,2,1]=", img.item(0,2,1))
print("读取像素点img[1,0,2]=", img.item(1,0,2))

修改后img=
 [[[ 64  26  12]
  [ 77  13  42]
  [ 71 255  27]
  [ 67  44  96]]

 [[ 27  61 255]
  [ 84  80  68]
  [255  66  47]
  [ 36  80  66]]]
读取像素点img[1,2,0]= 255
读取像素点img[0,2,1]= 255
读取像素点img[1,0,2]= 255


使用item,itemset对像素点值进行修改。